#!/bin/bash

# Script de Limpeza de Arquivos Obsoletos - NexoGeo v2.5
# Data: 2025-10-24
# Objetivo: Remover 62 arquivos obsoletos identificados

echo "🗑️  NexoGeo - Limpeza de Arquivos Obsoletos"
echo "=========================================="
echo ""

# Contador
TOTAL_FILES=0

# Função para remover arquivo
remove_file() {
    local file="$1"
    if [ -f "$file" ]; then
        git rm "$file" 2>/dev/null || rm -f "$file"
        echo "✅ Removido: $file"
        ((TOTAL_FILES++))
    else
        echo "⚠️  Não encontrado: $file"
    fi
}

echo "📋 Fase 1: Arquivos Temporários/Logs"
echo "-------------------------------------"
remove_file "build_output.txt"
remove_file "logs_temp.txt"
remove_file ".t.txt"
remove_file ".temp_db_url.txt"
remove_file ".deploy-trigger"
remove_file ".vercel-deploy-trigger"

echo ""
echo "📋 Fase 2: Planejamento Obsoleto"
echo "-------------------------------------"
remove_file "planejamento.txt"
remove_file "pranejamento.txt"
remove_file "PROXIMAS_ETAPAS.md"
remove_file "PROXIMO_PASSO_DEBUG.md"
remove_file "PLANO_INTEGRACAO_PUBLIC_PARTICIPANTS.md"

echo ""
echo "📋 Fase 3: Migrações Antigas (Já Executadas)"
echo "-------------------------------------"
remove_file "EXECUTAR_MIGRATION_AGORA.md"
remove_file "EXECUTAR_REGENERACAO_CREDENCIAIS.md"
remove_file "MIGRATION_MANUAL.md"
remove_file "MIGRATION_SPONSOR_FIELDS.md"
remove_file "PHONE_MIGRATION_INSTRUCTIONS.md"
remove_file "SPONSOR_FIELDS_SUMMARY.md"
remove_file "GUIA_MIGRACAO_NEON.md"
remove_file "INSTRUCOES_MIGRACAO_COMPLETA.md"
remove_file "MIGRACAO_README.md"
remove_file "setup-neon-database.md"
remove_file "NEON_BACKUP_GUIA.md"
remove_file "COPIAR_BANCO_DADOS.md"
remove_file "COPIAR_DADOS_INSTRUCOES.md"

echo ""
echo "📋 Fase 4: Correções Antigas/Redundantes"
echo "-------------------------------------"
remove_file "CORRECAO_APLICADA_PATROCINADOR.md"
remove_file "CORRECAO_ERRO_500_SPONSOR.md"
remove_file "CORRECAO_GERAR_LINKS.md"
remove_file "CORREÇÃO_SYNTAX_ERROR.md"
remove_file "CORRECAO_URGENTE_PATROCINADOR.md"
remove_file "CORRECOES_APLICADAS.md"
remove_file "CORRECOES_SEGURANCA_APLICADAS.md"
remove_file "CORREÇÕES_SESSAO_15-09-2025.md"
remove_file "CORRECOES_VERCEL.md"
remove_file "SOLUCAO_ERRO_LOGIN.md"
remove_file "SOLUCAO_FINAL_LINKS.md"
remove_file "RELATORIO-CORRECOES-2025-10-24.md"

echo ""
echo "📋 Fase 5: Pontos de Restauração Antigos"
echo "-------------------------------------"
remove_file "PONTO_RECUPERACAO_04-10-2025.md"
remove_file "PONTO_RESTAURACAO_15-09-2025.md"
remove_file "PONTO-RESTAURACAO-v1.3.0.md"
remove_file "PONTO-RESTAURACAO-v2.0.md"
remove_file "RESTAURACAO-v1.0.md"

echo ""
echo "📋 Fase 6: Diagnósticos/Análises Antigas"
echo "-------------------------------------"
remove_file "ANALISE_HAR_ERRO_500.md"
remove_file "DIAGNOSTICO_CAIXA_MISTERIOSA.md"
remove_file "AUDITORIA_CODIGO.md"
remove_file "AUDITORIA_SEGURANCA_CRITICA.md"
remove_file "COMPARATIVO_SCHEMAS.md"

echo ""
echo "📋 Fase 7: Verificações/Instruções Antigas"
echo "-------------------------------------"
remove_file "DESABILITAR_VERCEL_PROTECTION.md"
remove_file "VERIFICACAO_POS_DEPLOY_SUCESSO.md"
remove_file "VERIFICAR_DEPLOY.md"
remove_file "VERIFICAR_LOGS_VERCEL.md"
remove_file "BACKUP_INSTRUCOES.md"

echo ""
echo "📋 Fase 8: Melhorias Antigas"
echo "-------------------------------------"
remove_file "MELHORIAS.md"
remove_file "MELHORIAS_PAINEL_MAPAS.md"
remove_file "MELHORIAS-SISTEMA-AUDITORIA.md"
remove_file "MELHORIAS-v2.0.md"
remove_file "SIDEBAR_TEMAS_MELHORADO.md"

echo ""
echo "📋 Fase 9: Changelogs Específicos"
echo "-------------------------------------"
remove_file "CHANGELOG_TEMA.md"

echo ""
echo "📋 Fase 10: Arquivos de Agentes Redundantes"
echo "-------------------------------------"
remove_file "AGENT.md"
remove_file "AGENTS.md"
remove_file ".kilocodemodes"
remove_file ".roomodes"
remove_file ".rules"

echo ""
echo "📋 Fase 11: SQL/Banco Obsoleto"
echo "-------------------------------------"
remove_file "criar tabelas sql mysql.txt"
remove_file "criar tabelas sql postgres.txt"

echo ""
echo "📋 Fase 12: Documentação Obsoleta"
echo "-------------------------------------"
remove_file "SERVIDOR_LOCAL.md"
remove_file "TESTE_FUNCIONALIDADES.md"
remove_file "test-execution-report.md"
remove_file "MCP_GEMINI_SETUP.md"

echo ""
echo "=========================================="
echo "✅ Limpeza Concluída!"
echo "📊 Total de arquivos removidos: $TOTAL_FILES"
echo ""
echo "🔍 Arquivos Mantidos (Essenciais):"
echo "  - README.md"
echo "  - CLAUDE.md"
echo "  - MIGRATIONS.md"
echo "  - RESTORE_POINTS.md"
echo "  - CHANGELOG.md"
echo "  - CORRECAO-CONTAGENS-2025-10-24.md"
echo "  - DIAGNOSTICO-SORTEIO-2025-10-24.md"
echo "  - CORRECAO-SORTEIO-COMPLETA.md"
echo "  - .env.example"
echo ""
echo "⚠️  Próximos Passos:"
echo "1. Revisar mudanças: git status"
echo "2. Adicionar análise: git add ANALISE_ARQUIVOS_OBSOLETOS.md"
echo "3. Commit: git commit -m 'chore: Remove 62 arquivos obsoletos'"
echo "4. Push: git push"
echo ""
